### ISSUE TITLE
load time and memory

### ISSUE THREAD

**Issue by Monteo** [shirsig/Mail#34]
information form !!Warmup
			
[30] = {
["time"] = 0.9049999999999727,
["mem"] = 2990.199999999997,
["gc"] = true,
["name"] = "Mail",
			
			
[54] = {
["time"] = 0,
["mem"] = 177,
["name"] = "postal",

**Comment by Monteo** [comment]
guess what addon is now deleted?

**Comment by shirsig** [comment]
Hm, are you sure this is accurate? I made very small changes besides the renaming when I renamed it, nothing that would drastically affect startup, or that I could imagine anyway.

Got a "!!Warmup" addon from some collection and this is the output I get:

![Alt text](https://i.imgur.com/seVZ3l4.png)

**Comment by Monteo** [comment]
I have no idea 
![image](https://user-images.githubusercontent.com/24656088/32758075-2db7bcc8-c915-11e7-8c7e-8b61acb23bf5.png)


!toggle: enabled
BonusScanner: enabled
!!Warmup: enabled
Ace: enabled
AceAccept: enabled
AddOnOrganizer: enabled
Atlas: enabled
AtlasLoot: enabled
AtlasQuest: enabled
AutoBar: enabled
AutoProfit: enabled
aux-addon: enabled
aux_merchant_prices: enabled
avbars: enabled
Bagnon: enabled
Bagnon_Core: enabled
Bagnon_Forever: enabled
Bagnon_Options: enabled
Banana: enabled
Banknon: enabled
BEB: enabled
BEBOptions: enabled
BetterCharacterStats: enabled
BigWigs: enabled
Bongos: enabled
Bongos_ActionBar: enabled
Bongos_MapBar: enabled
Bongos_Options: enabled
Bongos_RollBar: enabled
Bongos_Stats: enabled
Cartographer: enabled
Catalyst: enabled
cdframes: enabled
ChatBar: enabled
ChatMOD: enabled
Chronometer: enabled
ClassicMouseover: enabled
ClassicSnowFall: enabled
Clean_Up_GUI: enabled
ColorGuildFrame-1.0: enabled
crafty: enabled
DoTimer: enabled
EnhancedFlightMap: enabled
EquipColor: enabled
EquipCompare: enabled
EzDismount: enabled
GFW_FeedOMatic: enabled
Gatherer: enabled
!ImprovedErrorFrame: enabled
KLHThreatMeter: enabled
LoseControl: enabled
LunaUnitFrames: enabled
Mail: enabled
MikScrollingBattleText: enabled
MikScrollingBattleTextOptions: enabled
MobHealth: enabled
MorunoRank: enabled
NamePlateFilter: enabled
CEnemyCastBar: enabled
CECB_Options: enabled
!OmniCC: enabled
Punschrulle: enabled
Rank14losSA: enabled
SimpleBagStats: enabled
SimpleCombatLog: enabled
SpecialTalent: enabled
SpecialTalentUI: enabled
SpellAlert: enabled
SpellAlertOptions: enabled
SuperMacro: enabled
TinyTip: enabled
TinyTipExtras: enabled
TinyTipOptions: enabled
TourGuide: enabled
TrinketMenu: enabled
VCB: enabled
vQueue: enabled
XLoot: enabled
YaHT: enabled
ZHunterMod: enabled
ShaguBoP: enabled
ShaguPlates: enabled
StylePoints: enabled
!Questie: enabled

**Comment by shirsig** [comment]
I assume it's not happening anymore now if it was also related to the mail update event.
