### ISSUE TITLE
Game freezes when clicking the "open mail" button

### ISSUE THREAD

**Issue by m33ts4k0z** [shirsig/Mail#35]
Hello and thanks for this addon. I noticed that when I
m opening my mail, the addon causes the game to freeze for some milliseconds but it happens with every mail in the opening sequence. This is not a major issue but since it happens even with just 2 mail in the mail box I thought I would report it.

**Comment by shirsig** [comment]
Implemented an optimized version of opening and sending that relies on other events rather than firing on every onupdate. Should still be equally fast (and hopefully still work in all cases ...)
