### ISSUE TITLE
[Feature request] Mail closing on second frame

### ISSUE THREAD

**Issue by fgsfdss** [shirsig/Mail#36]
When opening an inspection, guild pane, skill pane etc, the mailbox closes.

CT Mailmod is able to have the mail and one extra frame open at the same time. Is this something that could be done in Mail as well?

**Comment by shirsig** [comment]
Oh, actually this was broken by some pull request https://github.com/shirsig/Mail/pull/30. Thought I'd reverted it but apparently not. Fixed now, but I think the reason he wanted it was to prevent some other issue which will now be back I guess (probably a conflict with some other addon)
