### ISSUE TITLE
Destination priority (alts>friends>guild>strangers)

### ISSUE THREAD

**Issue by Bifidus** [shirsig/Mail#40]
I just switched from postal to mail without thinking about keeping postal addon folder around and... bad move ^^
The default behavior of postal was to propose all your alts on the same account as default destination. Once you at least press a letter,  alts came before friends, which came before strangers.
So for example, if Aaron is my alt, Abelinda my friend, and Abebe a stranger, when i send something, if i press the letter "a", postal was proposing Aaron first. Then if i continue and press b, Abelinda was proposed.
That behavior as disappeared with mail.
Can we have it back ?

Edit : false alert, it was just a matter of logging again all my alts, so the new addon can learn their existence.

**Comment by shirsig** [comment]
There were no strangers before. About the time of the name change autocompletion was extended to senders and recipients. But yeah, dont think I even considered the priority then. Makes sense and will be an easy change.

**Comment by Bifidus** [comment]
Can we also have an option about friends (disabling them in the sender list) ? It's easy to send them something by mistake...
Actually, an option for each (alts/friends/guild/strangers) could help.

**Comment by shirsig** [comment]
I've now changed it to prioritize by recency which i think makes even more sense than alts first. Whoever you've logged on as last, mailed to last or received from last will be the first in the autocomplete list (among the ones matching the entered string)
I don't like the idea of any options for mail, sorry.
