### ISSUE TITLE
[Bug] Sometimes, the mail stop to be autocollected

### ISSUE THREAD

**Issue by Bifidus** [shirsig/Mail#42]
No pop-up error, no message anywhere. It just stop. I have to click the button again. Sometimes several times in a row.

It's not 100% reproducible. It happen roughly 1 on 3 times i use the autocollect button.

**Comment by shirsig** [comment]
Newest version? Any special circumstances? can't reproduce it at all, tried 100+ mails.

**Comment by shirsig** [comment]
Nevermind, found the bug, was only happening when sending money.
