### ISSUE TITLE
[question] How to remove a recipient ?

### ISSUE THREAD

**Issue by Bifidus** [shirsig/Mail#43]
I put someone in my friendlist, name "XYZ". I have an alt on the same account, name "XXYZ". And another one on another account, name "XXXYZ".

By mistake, i send a mail to XYZ. To avoid the behavior of Mail addon of putting him in my recipients list, i remove him from my friendlist.
But he is still in the recipients list, forever.

How do i remove him of the recipients list ?

Also, to avoid these kind of mistakes, can we have colors ?
Green for alts, yellow for guild members, red for everyone else (including friends).

Even better : have a whitelist/blacklist of people to use/not use by default in the recipients list.

**Comment by shirsig** [comment]
It's not forever but for one month. If you want to delete it earlier you always delete it from the savedvariables file.
I don't think removing them is useful enough to make it a feature. In the newest version names should be sorted by time they were last seen so something that you didn't wanna add will get pushed down the list anyway.
The colors seem like a good idea, will try it to see if it doesn't look too ugly sometime.

**Comment by Bifidus** [comment]
One month, ok, i did not know.

> I don't think removing them is useful enough to make it a feature.
Right click and "delete that recipient" could have been handy, but yes, it's just comfort. I'll wait one month.

> In the newest version names should be sorted by time they were last seen
That sound like a problem : the most importants recipients are my alts. And i'll never "see" them, because they are on the same account, so they will always be down the list ?

**Comment by shirsig** [comment]
"Seen" means one of three things: you logged in as them, you sent a mail to them or you opened a mail from them. So any alt that you actively use will usually be at the top.

**Comment by Bifidus** [comment]
Sound good then :)
